### ISSUE TITLE
Chrome Extension seems to not be mapping consistently

### ISSUE THREAD

**Issue by geckoseo** [livestyle/sublime-text#5]
I have been noticing this a lot recently with the Alpha version.

If I open a remote stylesheet via sftp and edit the file directly on the server, at first LiveStyle seems to map it correctly to Sublime.

If I refresh the browser page though, the bi-directional mapping seems to break, and all the available stylesheets on the dropdown are no longer visible.

I then need to add the remote stylesheet as user stylesheet 1.

This still allows live update from Sublime to happen on the website, but the bi-direction mapping is broken, so any edits made in Chrome Dev tools does not update the stylesheet in Sublime.

If I close Dev Tools, then re-open it, all the stylesheets reappear in the LiveStyle dropdown in Chrome, and the bi-directional editing works again until I refresh the browser window, at which time it breaks again until I close Dev Tools.

It's possible this might be cache related, although I am struggling to find the root cause.

**Comment by sergeche** [comment]
I had similar issue too. AFAIK in only happens when DevTools are opened.
Did you removed previous versions of LiveStyle from Chrome and Sublime Text?

**Comment by sergeche** [comment]
PS: could you post new issue at https://github.com/livestyle/issues/issues?
It would be easier for me track them :)

**Comment by geckoseo** [comment]
I'll copy the ticket over to issues and we can pick it up again there..
