### ISSUE TITLE
Is there any chance this amazing product can support javascript as well

### ISSUE THREAD

**Issue by pingshunhuangalex** [livestyle/sublime-text#6]
Is there any chance this amazing product can support javascript as well? Thanks.

**Comment by sergeche** [comment]
I’m afraid there’s no easy way to do so. It’s quite possible to hot-reload some code points but the problem is that JS holds state which can’t be updated like that and code reload will lead to unpredictable results

**Comment by pingshunhuangalex** [comment]
Maybe let the plugin to refresh the page whenever the js is saved. It's not as elegant as real-time solution, but can be quite useful already.
